version: "3.8"

services:
  neo4j:
    image: neo4j:community-bullseye
    container_name: cartgenie-neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password123

  qdrant:
    image: qdrant/qdrant:v1.15.4
    container_name: cartgenie-qdrant
    ports:
      - "6333:6333" # gRPC
      - "6334:6334" # Web UI
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  neo4j_data:
  qdrant_data:
